CREATE ROLE DRINKMAP_APPLICATION;
ALTER ROLE [db_datareader] ADD MEMBER DRINKMAP_APPLICATION;
GRANT CONNECT TO DRINKMAP_APPLICATION;
GRANT SELECT TO DRINKMAP_APPLICATION;
GRANT INSERT ON OBJECT::[dbo].REVIEW_DRINK TO DRINKMAP_APPLICATION;
GRANT INSERT ON OBJECT::[dbo].REVIEW_LOCATION TO DRINKMAP_APPLICATION;
