------------------------------------------------------------------------------------------------------------------------------------------
CREATE FUNCTION SELECT_MIXED_DRINK(@SELECTED_NAME VARCHAR(MAX))
RETURNS TABLE 
AS
RETURN (
	SELECT
		MIXED_DRINK.NAME AS MIXED_DRINK_NAME,
		INSTRUCTIONS AS INSTRUCTIONS,
		INGREDIENT.NAME AS INGREDIENT_NAME,
		GLASSWARE.NAME AS GLASSWARE_NAME,
		INGREDIENT_MIX.RATIO AS INGREDIENT_MIX_RATIO,
		GARNISH_MIX.MIXTURE AS GARNISH_MIX_MIXTURE,
		GARNISH.NAME AS GARNISH_NAME,
		REVIEW_DRINK.RATING AS REVIEW_DRINK_RATING
	FROM MIXED_DRINK
		LEFT JOIN INGREDIENT_MIX ON MIXED_DRINK.ID = INGREDIENT_MIX.MIXED_DRINK_ID
		LEFT JOIN INGREDIENT ON INGREDIENT_MIX.INGREDIENT_ID = INGREDIENT.ID
		LEFT JOIN INGREDIENT_TYPE ON INGREDIENT.INGREDIENT_TYPE_ID = INGREDIENT_TYPE.ID
		LEFT JOIN GLASSWARE ON MIXED_DRINK.GLASS_ID = GLASSWARE.ID
		LEFT JOIN GARNISH_MIX ON MIXED_DRINK.ID = GARNISH_MIX.MIXED_DRINK_ID
		LEFT JOIN GARNISH ON GARNISH_MIX.GARNISH_ID = GARNISH.ID
		LEFT JOIN REVIEW_DRINK ON MIXED_DRINK.ID = REVIEW_DRINK.MIXED_DRINK_ID
	WHERE MIXED_DRINK.NAME = @SELECTED_NAME
);
GO
------------------------------------------------------------------------------------------------------------------------------------------